# -*- coding: utf-8 -*-
"""Tugasakhir (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WvyM2C260jvlrQ45Ob7TzcZ2COB7ChwR
"""

!pip install catboost

!pip install pandas numpy scikit-learn imbalanced-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_validate

from sklearn.ensemble import RandomForestClassifier
from catboost import CatBoostClassifier
from sklearn.ensemble import VotingClassifier

from collections import Counter
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import classification_report
from imblearn.over_sampling import BorderlineSMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.inspection import permutation_importance
import textwrap
import warnings

warnings.filterwarnings('ignore')

"""# Import dataset"""

df=pd.read_csv('/content/sample_data/CVD_cleaned.csv')

"""# Copy dataset"""

df1=df.copy()

"""# Tranformasi data"""

df1['BMI_Category'] = pd.cut(df1['BMI'], bins=[0, 18.5, 25, 30, np.inf], labels=['Underweight(<18.5)', 'Normal(18.5–24.9)', 'Overweight(25–29.9)', 'Obesity(>=30)'], right=False).astype('object')

"""# Informasi data

jumlah data dan kolom
"""

df1.shape

"""informasi data"""

df1.info()

"""10 data teratas"""

df1.head((10))

"""10 data terbawah"""

df1.tail((10))

"""# Preprocessing data

data duplikat
"""

duplicates = df1[df1.duplicated()]
print("Total Duplicates rows observed:", duplicates.shape[0])
print("Dropping duplicates")
# Dropping duplicates
print("Shape before dropping duplicates: ", df1.shape[0])
df1.drop_duplicates(inplace=True)
df1.reset_index(drop=True, inplace=True)
print("Shape after dropping duplicates: ", df1.shape[0])
duplicates_after_drop = df1[df1.duplicated()]
print("Total Duplicates rows observed after dropping:", duplicates_after_drop.shape[0])

"""missing values"""

total = df1.isnull().sum().sort_values(ascending=False)
percent = (df1.isnull().sum() / df1.isnull().count()).sort_values(ascending=False)
missing_df1 = pd.concat([total, percent*100], axis=1, keys=["Total", "Percent(%)"])
missing_df1

"""# Exploratory data analys

kategori variabel data
"""

# Numerical variables:
num_cols = ['Height_(cm)', 'Weight_(kg)',  'Alcohol_Consumption','BMI','Fruit_Consumption', 'Green_Vegetables_Consumption','FriedPotato_Consumption']

# Categorical variables:
cat_cols = [ 'Exercise', 'Heart_Disease', 'Skin_Cancer','Other_Cancer', 'Depression',  'Arthritis', 'Sex', 'Smoking_History']

# Ordinal variables
ord_cols = ['General_Health', 'Checkup','Diabetes','Age_Category', 'BMI_Category']

"""unique values numerik"""

print(f"[Unique Values in {len(num_cols)} Numerical Variables]\n")
for num_col in num_cols:
    unique_values = df1[num_col].unique()
    min_value = unique_values.min()
    max_value = unique_values.max()
    print(f"* {num_col} : {len(unique_values)} Unique Values, ranging from {min_value} to {max_value}")

"""unique values kolom category"""

print(f"[Unique Values in {len(cat_cols)} Categorical Variables]\n")

for cat_col in cat_cols:
    print("* {} : {} Unique Values =>".format(cat_col, df1[cat_col].nunique()), df1[cat_col].unique())

"""unique values kolom ordinal"""

print(f"[Unique Values in {len(ord_cols)} Ordinal Variables]\n")

for ord_col in ord_cols:
    print("* {} : {} Unique Values =>".format(ord_col, df1[ord_col].nunique()), df1[ord_col].unique())

"""univariate analys numerik col"""

n_rows, n_cols = 3, 3
fig, ax = plt.subplots(n_rows, n_cols, figsize=(16, 12))
ax = ax.flatten()

for idx, col in enumerate(num_cols):

    sns.histplot(
        data=df1,
        x=col,
        bins=30,
        stat='density',
        kde=False,
        ax=ax[idx]
    )
    ax[idx].set_title(f'{col} (Histogram)', fontsize=12)
    ax[idx].set_xlabel('')
    ax[idx].set_ylabel('Density')


for j in range(len(num_cols), len(ax)):
    fig.delaxes(ax[j])

fig.tight_layout()
plt.show()

"""univariate analys category col"""

n_rows, n_cols = 3, 3
fig, ax = plt.subplots(n_rows, n_cols, figsize=(15, 15))

for i, cat_col in enumerate(cat_cols[:9]):
    i_row, i_col = i // n_cols, i % n_cols
    rects = sns.countplot(x=cat_col, data=df1, ax=ax[i_row, i_col], palette=["#87CEEB", "#FFA07A"])
    for rect in rects.patches:
        height = rect.get_height()
        ax[i_row, i_col].text(rect.get_x() + rect.get_width() / 2., height + 12, "{:1.1f}% / {:d}".format(height / len(df1) * 100, height.astype(int)), ha='center', bbox=dict(facecolor='none', edgecolor='black', boxstyle='round', linewidth=0.5))
    ax[i_row, i_col].set_title(f'{cat_col} Distribution', fontsize=14)
    ax[i_row, i_col].set_xlabel("")
    ax[i_row, i_col].set_ylabel("Number of Patients")
    ax[i_row, i_col].set_ylim([0, max([rect.get_height() for rect in rects.patches]) * 1.2])


if len(cat_cols) < 9:
    for i in range(len(cat_cols), n_rows * n_cols):
        i_row, i_col = i // n_cols, i % n_cols
        ax[i_row, i_col].axis('off')

fig.tight_layout()
plt.show()

"""oridinal col"""

labels_wrapped = {
    'General_Health': [ textwrap.fill(lbl, width=10) for lbl in ['Poor', 'Very Good', 'Good', 'Fair', 'Excellent'] ],
    'Checkup': [ textwrap.fill(lbl, width=12) for lbl in [ 'Within the past 2 years', 'Within the past year', '5 or more years ago', 'Within the past 5 years', 'Never' ] ],
    'Diabetes': [ textwrap.fill(lbl, width=12) for lbl in [ 'No', 'Yes', 'No, pre-diabetes or borderline diabetes', 'Yes, but female told only during pregnancy' ] ],
    'Age_Category': [ textwrap.fill(lbl, width=8) for lbl in ['18-24', '25-29', '30-34', '35-39', '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74', '75-79', '80+'] ],
    'BMI_Category': [ textwrap.fill(lbl, width=15) for lbl in ['Underweight(<18.5)', 'Normal(18.5–24.9)', 'Overweight(25–29.9)', 'Obesity(>=30)'] ]
}

orders = {
    'General_Health': ['Poor', 'Very Good', 'Good', 'Fair', 'Excellent'],
    'Checkup': [ 'Within the past 2 years', 'Within the past year', '5 or more years ago', 'Within the past 5 years', 'Never' ],
    'Diabetes': [ 'No', 'Yes', 'No, pre-diabetes or borderline diabetes', 'Yes, but female told only during pregnancy' ],
    'Age_Category': [ '18-24', '25-29', '30-34', '35-39', '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74', '75-79', '80+' ],
    'BMI_Category': ['Underweight(<18.5)', 'Normal(18.5–24.9)', 'Overweight(25–29.9)', 'Obesity(>=30)']
}

master_palette = sns.color_palette("pastel", 13)
fig, axes = plt.subplots(2, 3, figsize=(18, 12)) # diubah menjadi 2x3
axes = axes.flatten()

for idx, col in enumerate(ord_cols + ['BMI_Category']): # tambahkan BMI_Category
    ax = axes[idx]
    n_cat = len(orders[col])
    pal = master_palette[:n_cat]
    sns.countplot( x=col, data=df1, order=orders[col], palette=pal, ax=ax )
    ax.set_xticklabels(labels_wrapped[col], rotation=45, ha="right", fontsize=11)
    ax.set_title(f"{col.replace('_', ' ')} Distribution", fontsize=16, pad=12)
    ax.set_xlabel("")
    ax.set_ylabel("Number of Patients", fontsize=12)
    total = len(df1)
    for p in ax.patches:
        height = p.get_height()
        pct = (height / total) * 100
        xloc = p.get_x() + p.get_width() / 2
        yloc = height + total * 0.005
        ax.text( xloc, yloc, f"{pct:1.1f}%\n{int(height):,}", ha="center", va="bottom", fontsize=10, bbox=dict(facecolor="white", edgecolor="gray", boxstyle="round,pad=0.2", linewidth=0.5) )
    max_h = max(p.get_height() for p in ax.patches)
    ax.set_ylim(0, max_h * 1.25)

plt.tight_layout()
plt.show()

"""Univariate analysis

numerik col
"""

# Buat grid 3x3
fig, axes = plt.subplots(3, 3, figsize=(15, 15))
axes_flat = axes.flatten()

# Loop setiap kolom
for i, col in enumerate(num_cols):
    ax = axes_flat[i]
    # Hitung jumlah bin berdasarkan sqrt dari jumlah unique, minimal 10 bin
    nunique = df1[col].nunique()
    bins = int(np.ceil(np.sqrt(nunique)))
    bins = max(bins, 10)

    # Plot untuk Heart_Disease = 'No'
    sns.histplot(
        df1[df1['Heart_Disease'] == 'No'][col].dropna(),
        bins=bins,
        label='No',
        alpha=0.5,
        kde=False,
        ax=ax
    )
    # Plot untuk Heart_Disease = 'Yes'
    sns.histplot(
        df1[df1['Heart_Disease'] == 'Yes'][col].dropna(),
        bins=bins,
        label='Yes',
        alpha=0.5,
        kde=False,
        ax=ax
    )

    ax.set_title(f'{col} vs Heart_Disease', fontsize=12)
    ax.set_xlabel(col, fontsize=10)
    ax.set_ylabel('Count', fontsize=10)
    ax.legend(title='Heart_Disease')
    ax.grid(axis='y', linestyle='--', alpha=0.5)

# Matikan sisa subplot (2 sisa dari 9)
for j in range(len(num_cols), 9):
    axes_flat[j].axis('off')

plt.tight_layout()
plt.show()

"""category col"""

n_rows, n_cols = 3, 3
fig, axes = plt.subplots(n_rows, n_cols, figsize=(18, 12))
fig.suptitle("Heart Disease by Patient Characteristics\n", fontsize=16, fontweight='bold')

cat_cols = ['Exercise', 'Skin_Cancer', 'Other_Cancer', 'Depression',
            'Arthritis', 'Sex', 'Smoking_History']

total = len(df1)

for i, col in enumerate(cat_cols):
    i_row, i_col = divmod(i, n_cols)
    ax = axes[i_row, i_col]


    rects = sns.countplot(x=col, hue="Heart_Disease", data=df1, ax=ax)


    for p in rects.patches:
        height = p.get_height()
        if height > 0:
            pct = height / total * 100
            ax.text(
                p.get_x() + p.get_width() / 2,
                height * 1.01,
                f"{pct:.1f}% ({int(height)})",
                ha='center',
                va='bottom',
                fontsize=9,
                bbox=dict(facecolor='white', edgecolor='gray', boxstyle='round,pad=0.2', linewidth=0.5)
            )

    ax.set_xlabel(col)
    ax.set_ylabel("Number of Patients")
    ax.set_title(f'Heart Disease cases by {col}')

for j in range(len(cat_cols), n_rows * n_cols):
    i_row, i_col = divmod(j, n_cols)
    axes[i_row, i_col].axis('off')

fig.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""ordinal col"""

category_orders = {
    'General_Health': ['Poor', 'Fair', 'Good', 'Very Good', 'Excellent'],
    'Checkup': ['Never', '5 or more years ago', 'Within the past 5 years', 'Within the past 2 years', 'Within the past year'],
    'Diabetes': ['No', 'No, pre-diabetes or borderline diabetes', 'Yes, but female told only during pregnancy', 'Yes'],
    'Age_Category': ['18-24', '25-29', '30-34', '35-39', '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74', '75-79', '80+'],
    'BMI_Category': ['Underweight(<18.5)', 'Normal(18.5–24.9)', 'Overweight(25–29.9)', 'Obesity(>=30)']
}

fig = plt.figure(figsize=(18, 24))
gs = fig.add_gridspec(3, 2, hspace=0.5, wspace=0.4)
palette = {"No": "#4C72B0", "Yes": "#DD8452"}
total = len(df1)

def plot_ordinal(ax, col_name, order_list, show_legend=False, rotate_xticks=30):
    sns.countplot( x=col_name, hue="Heart_Disease", data=df1, order=order_list, palette=palette, ax=ax, dodge=True )
    counts = df1.groupby([col_name, 'Heart_Disease']).size()
    max_count = counts.max() if not counts.empty else 0
    ax.set_ylim(0, max_count * 1.1)
    for p in ax.patches:
        h = p.get_height()
        if h > 0:
            pct = h / total * 100
            offset = max_count * 0.05
            ax.text( p.get_x() + p.get_width() / 2, h + offset, f"{int(h)}\n{pct:.1f}%", ha='center', va='bottom', fontsize=10, bbox=dict(facecolor='white', edgecolor='gray', boxstyle='round,pad=0.2') )
    ax.set_title(col_name.replace('_', ' '), fontsize=12, pad=10)
    ax.set_xlabel('')
    ax.set_ylabel("Jumlah Pasien", fontsize=10)
    ax.tick_params(axis='x', rotation=rotate_xticks, labelsize=9)
    ax.tick_params(axis='y', labelsize=9)
    ax2 = ax.twinx()
    sns.pointplot( x=col_name, y="Heart_Disease", data=df1, estimator=lambda x: np.mean(x == 'Yes'), order=order_list, errwidth=0, marker='X', color='black', ax=ax2 )
    ax2.set_ylim(0, 1)
    ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f"{int(y * 100)}%"))
    ax2.set_ylabel("% Penyakit Jantung", fontsize=10)
    ax2.tick_params(axis='y', labelsize=9)
    ax2.yaxis.tick_right()
    ax2.yaxis.set_label_position('right')
    if show_legend:
        ax.legend( title='Heart Disease', loc='upper center', bbox_to_anchor=(0.5, 1.15), fontsize=10, title_fontsize=11 )
    else:
        ax.get_legend().remove()

ax0 = fig.add_subplot(gs[0, 0])
plot_ordinal( ax=ax0, col_name='General_Health', order_list=category_orders ['General_Health'], show_legend=True, rotate_xticks=30 )

ax1 = fig.add_subplot(gs[0, 1])
plot_ordinal( ax=ax1, col_name='Checkup', order_list=category_orders['Checkup'], show_legend=False, rotate_xticks=30 )

ax2 = fig.add_subplot(gs[1, 0])
plot_ordinal( ax=ax2, col_name='Diabetes', order_list=category_orders['Diabetes'], show_legend=False, rotate_xticks=45 )

ax3 = fig.add_subplot(gs[1, 1])
plot_ordinal( ax=ax3, col_name='Age_Category', order_list=category_orders['Age_Category'], show_legend=False, rotate_xticks=45 )

ax4 = fig.add_subplot(gs[2, 0])
plot_ordinal( ax=ax4, col_name='BMI_Category', order_list=category_orders['BMI_Category'], show_legend=False, rotate_xticks=45 )

ax5 = fig.add_subplot

"""multivariate analys

numerik col
"""



"""category col"""



"""ordinal col"""



"""data statistik numerik col"""

df1.describe().transpose()

"""box plot"""

fig, axs = plt.subplots(1, 7, figsize=(20, 5))

axs[0].boxplot(df1['Height_(cm)'])
axs[0].set_title('Height_(cm)')

axs[1].boxplot(df1['Weight_(kg)'])
axs[1].set_title('Weight_(kg)')

axs[2].boxplot(df1['Alcohol_Consumption'])
axs[2].set_title('Alcohol_Consumption')

axs[3].boxplot(df1['BMI'])
axs[3].set_title('BMI')

axs[4].boxplot(df1['Fruit_Consumption'])
axs[4].set_title('Fruit_Consumption')

axs[5].boxplot(df1['Green_Vegetables_Consumption'])
axs[5].set_title('Green_Vegetables_Consumption')

axs[6].boxplot(df1['FriedPotato_Consumption'])
axs[6].set_title('FriedPotato_Consumption')

plt.tight_layout()
plt.show()

"""## Train Model dan Test Model

Copy dataset
"""

df2=df.copy()

df2.head()

df2.tail()

"""feature enginering data"""

df2['BMI_Category'] = pd.cut(df2['BMI'], bins=[0, 18.5, 25, 30, np.inf], labels=['Underweight(<18.5)', 'Normal(18.5–24.9)', 'Overweight(25–29.9)', 'Obesity(>=30)'], right=False).astype('object')

"""Preprocessing"""

duplicates = df2[df2.duplicated()]
print("Total Duplicates rows observed:", duplicates.shape[0])
print("Dropping duplicates")
print("Shape before dropping duplicates: ", df2.shape[0])
df2.drop_duplicates(inplace=True)
df2.reset_index(drop=True, inplace=True)
print("Shape after dropping duplicates: ", df2.shape[0])
duplicates_after_drop = df2[df2.duplicated()]
print("Total Duplicates rows observed after dropping:", duplicates_after_drop.shape[0])

total = df2.isnull().sum().sort_values(ascending=False)
percent = (df2.isnull().sum() / df2.isnull().count()).sort_values(ascending=False)
missing_df2 = pd.concat([total, percent*100], axis=1, keys=["Total", "Percent(%)"])
missing_df2

"""Encoding"""

binary_cols = ['Exercise', 'Heart_Disease', 'Skin_Cancer', 'Other_Cancer','Depression', 'Arthritis', 'Sex', 'Smoking_History']

ordinal_cols = {
    'General_Health': ['Poor', 'Fair', 'Good', 'Very Good', 'Excellent'],
    'Checkup': ['Never', '5 or more years ago', 'Within the past 5 years',
                'Within the past 2 years', 'Within the past year'],
    'Diabetes': ['No', 'No, pre-diabetes or borderline diabetes',
                 'Yes, but female told only during pregnancy', 'Yes'],
    'Age_Category': ['18-24', '25-29', '30-34', '35-39', '40-44', '45-49',
                     '50-54', '55-59', '60-64', '65-69', '70-74', '75-79', '80+'],
    'BMI_Category': ['Underweight(<18.5)', 'Normal(18.5–24.9)', 'Overweight(25–29.9)',
                     'Obesity(>=30)']}

for col in binary_cols:
    le = LabelEncoder()
    df2[col] = le.fit_transform(df2[col])
    print(f"{col} mapping: {dict(zip(le.classes_, le.transform(le.classes_)))}")

for col, categories in ordinal_cols.items():
    oe = OrdinalEncoder(categories=[categories])
    df2[col] = oe.fit_transform(df2[[col]]).astype(int)
    print(f"{col} mapping: {dict(zip(categories, range(len(categories))))}")

"""Correlation matrix"""

correlation_matrix = df2.corr()

plt.figure(figsize=(20, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

"""feature selection"""

features = ['Age_Category', 'Diabetes', 'Arthritis', 'General_Health', 'Exercise', 'BMI', 'Smoking_History', 'Sex']
target = 'Heart_Disease'

"""train test split"""

X = df2[features]
y = df2[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""smote"""

smote = BorderlineSMOTE(sampling_strategy=1.0 , random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

X_train, X_test, y_train, y_test = train_test_split(X_train_smote, y_train_smote, test_size=0.2, random_state=42)

def plot_class_distribution(y_data, title, ax, colors):
    counter = Counter(y_data)
    labels = ['Kelas 0', 'Kelas 1']
    values = [counter[0], counter[1]]

    bars = ax.bar(labels, values, color=colors, edgecolor='black')
    ax.set_title(title, fontsize=14)
    ax.set_ylabel('Jumlah', fontsize=12)
    ax.set_xlabel('Kelas', fontsize=12)
    ax.grid(axis='y', linestyle='--', alpha=0.7)

    # Tambahkan label di atas bar
    for bar in bars:
        yval = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2, yval + 1000, f'{yval:,}',
                ha='center', va='bottom', fontsize=10, fontweight='bold')

# Plot
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
plot_class_distribution(y_train, 'Distribusi Kelas y_train', axes[0], ['#1f77b4', '#ff7f0e'])
plot_class_distribution(y_train_smote, 'Distribusi Kelas y_train_smote', axes[1], ['#1f77b4', '#ff7f0e'])

plt.tight_layout()
plt.show()

sampling_strategy = {0: 5078, 1: 5078}

# Inisialisasi RandomUnderSampler
rus = RandomUnderSampler(sampling_strategy=sampling_strategy, random_state=42)

# Terapkan under-sampling pada data test
X_test_resampled, y_test_resampled = rus.fit_resample(X_test, y_test)

# Verifikasi distribusi kelas setelah under-sampling
print("Distribusi kelas setelah under-sampling:")
print(y_test_resampled.value_counts())

"""# Random forest"""

rf1 = RandomForestClassifier(
    n_estimators=400,
    max_depth=15,
    min_samples_split=8,
    min_samples_leaf=6,
    max_features='sqrt',
    class_weight='balanced_subsample',
    random_state=42
)
rf1.fit(X_train_smote, y_train_smote)

rf1_predictions_train = rf1.predict(X_train_smote)
rf1_predictions_test = rf1.predict(X_test_resampled)

accuracy_train = accuracy_score(y_train_smote, rf1_predictions_train)
print(f"Random Forest Classifier Train Accuracy: {accuracy_train:.2f}")
print("Random Forest Classifier Train Classification Report:")
print(classification_report(y_train_smote, rf1_predictions_train))
print("Random Forest Classifier Train Confusion Matrix:")
print(confusion_matrix(y_train_smote, rf1_predictions_train))

accuracy_test = accuracy_score(y_test_resampled, rf1_predictions_test)
print(f"Random Forest Classifier Test Accuracy: {accuracy_test:.2f}")
print("Random Forest Classifier Test Classification Report:")
print(classification_report(y_test_resampled, rf1_predictions_test))
print("Random Forest Classifier Test Confusion Matrix:")
print(confusion_matrix(y_test_resampled, rf1_predictions_test))

print(f"Selisih Akurasi: {abs(accuracy_train - accuracy_test):.2f}")

"""# feature importance rf1"""

print("Melatih model Random Forest...")
rf1 = RandomForestClassifier(
    n_estimators=400,
    max_depth=15,
    min_samples_split=8,
    min_samples_leaf=6,
    max_features='sqrt',
    class_weight='balanced_subsample',
    random_state=42
)
rf1.fit(X_train_smote, y_train_smote)
print("Model selesai dilatih.")

accuracy_test = rf1.score(X_test_resampled, y_test_resampled)
print(f"Akurasi Awal Model di Data Tes: {accuracy_test:.4f}\n")

print("Menghitung Permutation Importance pada data tes...")
result = permutation_importance(
    rf1,
    X_test_resampled,
    y_test_resampled,
    n_repeats=10,
    random_state=42,
    n_jobs=-1,
    scoring='accuracy'
)
print("Perhitungan selesai.\n")

sorted_importances_idx = result.importances_mean.argsort()[::-1]

importance_summary = pd.DataFrame({
    'Fitur': X_test_resampled.columns[sorted_importances_idx],
    'Penurunan Akurasi': result.importances_mean[sorted_importances_idx],
    'Std Dev': result.importances_std[sorted_importances_idx]
})

importance_summary['Prediksi Akurasi Baru'] = accuracy_test - importance_summary['Penurunan Akurasi']

print("="*80)
print("                  HASIL PERMUTATION IMPORTANCE (TERURUT)")
print(f"                  Akurasi Awal Model: {accuracy_test:.4f}")
print("="*80)
print("Menunjukkan estimasi akurasi jika sebuah fitur dihilangkan (diacak).")

pd.options.display.float_format = '{:,.4f}'.format
print(importance_summary.to_string())
print("="*80)

rf2 = RandomForestClassifier(
    n_estimators=500,
    max_depth=25,
    min_samples_split=2,
    min_samples_leaf=2,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42
)
rf2.fit(X_train_smote, y_train_smote)

rf2_predictions_train = rf2.predict(X_train_smote)
rf2_predictions_test = rf2.predict(X_test_resampled)

accuracy_train = accuracy_score(y_train_smote, rf2_predictions_train)
print(f"Random Forest Classifier Train Accuracy: {accuracy_train:.2f}")
print("Random Forest Classifier Train Classification Report:")
print(classification_report(y_train_smote, rf2_predictions_train))
print("Random Forest Classifier Train Confusion Matrix:")
print(confusion_matrix(y_train_smote, rf2_predictions_train))

accuracy_test = accuracy_score(y_test_resampled, rf2_predictions_test)
print(f"Random Forest Classifier Test Accuracy: {accuracy_test:.2f}")
print("Random Forest Classifier Test Classification Report:")
print(classification_report(y_test_resampled, rf2_predictions_test))
print("Random Forest Classifier Test Confusion Matrix:")
print(confusion_matrix(y_test_resampled, rf2_predictions_test))

print(f"Selisih Akurasi: {abs(accuracy_train - accuracy_test):.2f}")

"""# feature importance rf2"""

print("Melatih model Random Forest (rf2)...")

rf2 = RandomForestClassifier(
    n_estimators=500,
    max_depth=25,
    min_samples_split=2,
    min_samples_leaf=2,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42
)
rf2.fit(X_train_smote, y_train_smote)
print("Model selesai dilatih.")


accuracy_test = rf2.score(X_test_resampled, y_test_resampled)
print(f"Akurasi Awal Model (rf2) di Data Tes: {accuracy_test:.4f}\n")


print("Menghitung Permutation Importance pada data tes untuk model rf2...")
result = permutation_importance(
    rf2,
    X_test_resampled,
    y_test_resampled,
    n_repeats=10,
    random_state=42,
    n_jobs=-1,
    scoring='accuracy'
)
print("Perhitungan selesai.\n")

sorted_importances_idx = result.importances_mean.argsort()[::-1]

importance_summary = pd.DataFrame({
    'Fitur': X_test_resampled.columns[sorted_importances_idx],
    'Penurunan Akurasi': result.importances_mean[sorted_importances_idx],
    'Std Dev': result.importances_std[sorted_importances_idx]
})

importance_summary['Prediksi Akurasi Baru'] = accuracy_test - importance_summary['Penurunan Akurasi']

print("="*80)
print("                  HASIL PERMUTATION IMPORTANCE (MODEL RF2)")
print(f"                  Akurasi Awal Model: {accuracy_test:.4f}")
print("="*80)
print("Menunjukkan estimasi akurasi jika sebuah fitur dihilangkan (diacak).")
pd.options.display.float_format = '{:,.4f}'.format
print(importance_summary.to_string())
print("="*80)

rf3 = RandomForestClassifier(
    n_estimators=600,
    max_depth=20,
    min_samples_split=3,
    min_samples_leaf=3,
    max_features='log2',
    class_weight='balanced',
    random_state=42
)
rf3.fit(X_train_smote, y_train_smote)

rf3_predictions_train = rf3.predict(X_train_smote)
rf3_predictions_test = rf3.predict(X_test_resampled)

accuracy_train = accuracy_score(y_train_smote, rf3_predictions_train)
print(f"Random Forest Classifier Train Accuracy: {accuracy_train:.2f}")
print("Random Forest Classifier Train Classification Report:")
print(classification_report(y_train_smote, rf3_predictions_train))
print("Random Forest Classifier Train Confusion Matrix:")
print(confusion_matrix(y_train_smote, rf3_predictions_train))

accuracy_test = accuracy_score(y_test_resampled, rf3_predictions_test)
print(f"Random Forest Classifier Test Accuracy: {accuracy_test:.2f}")
print("Random Forest Classifier Test Classification Report:")
print(classification_report(y_test_resampled, rf3_predictions_test))
print("Random Forest Classifier Test Confusion Matrix:")
print(confusion_matrix(y_test_resampled, rf3_predictions_test))

print(f"Selisih Akurasi: {abs(accuracy_train - accuracy_test):.2f}")

"""# feature importance rf3"""

rf3 = RandomForestClassifier(
    n_estimators=600,
    max_depth=20,
    min_samples_split=3,
    min_samples_leaf=3,
    max_features='log2',
    class_weight='balanced',
    random_state=42
)
rf3.fit(X_train_smote, y_train_smote)
print("Model selesai dilatih.")

accuracy_test = rf3.score(X_test_resampled, y_test_resampled)
print(f"Akurasi Awal Model (rf3) di Data Tes: {accuracy_test:.4f}\n")

print("Menghitung Permutation Importance pada data tes untuk model rf3...")
result = permutation_importance(
    rf3,
    X_test_resampled,
    y_test_resampled,
    n_repeats=10,
    random_state=42,
    n_jobs=-1,
    scoring='accuracy'
)
print("Perhitungan selesai.\n")


sorted_importances_idx = result.importances_mean.argsort()[::-1]

importance_summary = pd.DataFrame({
    'Fitur': X_test_resampled.columns[sorted_importances_idx],
    'Penurunan Akurasi': result.importances_mean[sorted_importances_idx],
    'Std Dev': result.importances_std[sorted_importances_idx]
})

importance_summary['Prediksi Akurasi Baru'] = accuracy_test - importance_summary['Penurunan Akurasi']

pd.options.display.float_format = '{:,.4f}'.format

print("="*80)
print("                  HASIL PERMUTATION IMPORTANCE (MODEL RF3)")
print(f"                  Akurasi Awal Model: {accuracy_test:.4f}")
print("="*80)
print("Menunjukkan estimasi akurasi jika sebuah fitur dihilangkan (diacak).")
print(importance_summary.to_string())
print("="*80)

"""Visualisasi perbandingan model"""

models = ['rf1', 'rf2', 'rf3']
train_accuracies = [0.85, 0.94, 0.91]
test_accuracies = [0.85, 0.94, 0.91]

bar_width = 0.4
x = np.arange(len(models))
plt.figure(figsize=(10, 6))
plt.bar(x - bar_width/2, train_accuracies, bar_width, label='Train Accuracy', color='#1f77b4')
plt.bar(x + bar_width/2, test_accuracies, bar_width, label='Test Accuracy', color='#2ca02c')

for i, (xt, yt) in enumerate(zip(x, train_accuracies)):
    plt.text(xt - bar_width/2, yt + 0.005, f'{yt:.2f}', ha='center', va='bottom', color='#1f77b4')
for i, (xt, yt) in enumerate(zip(x, test_accuracies)):
    plt.text(xt + bar_width/2, yt + 0.005, f'{yt:.2f}', ha='center', va='bottom', color='#2ca02c')

plt.xticks(x, models, fontsize=11)
plt.yticks(fontsize=11)
plt.xlabel('Model', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.title('Akurasi Train dan Test\nRandom Forest Classifier', fontsize=14, fontweight='bold')
plt.ylim(0.80, 1.00)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(fontsize=11)
plt.tight_layout()

plt.show()

"""# Catboost"""

cb1 = CatBoostClassifier(
    iterations=400,
    depth=8,
    learning_rate=0.05,
    loss_function='Logloss',
    eval_metric='Accuracy',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced'
)
cb1.fit(X_train_smote, y_train_smote)

cb1_predictions_train = cb1.predict(X_train_smote)
cb1_predictions_test = cb1.predict(X_test_resampled)

accuracy_train = accuracy_score(y_train_smote, cb1_predictions_train)
print(f"CatBoost Classifier Train Accuracy: {accuracy_train:.2f}")
print("CatBoost Classifier Train Classification Report:")
print(classification_report(y_train_smote, cb1_predictions_train))
print("CatBoost Classifier Train Confusion Matrix:")
print(confusion_matrix(y_train_smote, cb1_predictions_train))

accuracy_test = accuracy_score(y_test_resampled, cb1_predictions_test)
print(f"CatBoost Classifier Test Accuracy: {accuracy_test:.2f}")
print("CatBoost Classifier Test Classification Report:")
print(classification_report(y_test_resampled, cb1_predictions_test))
print("CatBoost Classifier Test Confusion Matrix:")
print(confusion_matrix(y_test_resampled, cb1_predictions_test))

print(f"Selisih Akurasi: {abs(accuracy_train - accuracy_test):.2f}")

"""# feature importance"""

cb1 = CatBoostClassifier(
    iterations=400,
    depth=8,
    learning_rate=0.05,
    loss_function='Logloss',
    eval_metric='Accuracy',
    random_state=42,
    verbose=0, # verbose=0 untuk menonaktifkan output saat training
    auto_class_weights='Balanced'
)
cb1.fit(X_train_smote, y_train_smote)
print("Model selesai dilatih.")

accuracy_test = cb1.score(X_test_resampled, y_test_resampled)
print(f"Akurasi Awal Model (cb1) di Data Tes: {accuracy_test:.4f}\n")


print("Menghitung Permutation Importance pada data tes untuk model CatBoost...")
result = permutation_importance(
    cb1,
    X_test_resampled,
    y_test_resampled,
    n_repeats=10,
    random_state=42,
    n_jobs=-1, # Gunakan semua core CPU
    scoring='accuracy'
)
print("Perhitungan selesai.\n")

sorted_importances_idx = result.importances_mean.argsort()[::-1]

importance_summary = pd.DataFrame({
    'Fitur': X_test_resampled.columns[sorted_importances_idx],
    'Penurunan Akurasi': result.importances_mean[sorted_importances_idx],
    'Std Dev': result.importances_std[sorted_importances_idx]
})

importance_summary['Prediksi Akurasi Baru'] = accuracy_test - importance_summary['Penurunan Akurasi']

pd.options.display.float_format = '{:,.4f}'.format
print("="*80)
print("                  HASIL PERMUTATION IMPORTANCE (MODEL CATBOOST)")
print(f"                  Akurasi Awal Model: {accuracy_test:.4f}")
print("="*80)
print("Menunjukkan estimasi akurasi jika sebuah fitur dihilangkan (diacak).")
print(importance_summary.to_string())
print("="*80)

cb2 = CatBoostClassifier(
    iterations=800,
    depth=12,
    learning_rate=0.01,
    loss_function='Logloss',
    eval_metric='Accuracy',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=3
)
cb2.fit(X_train_smote, y_train_smote)
cb2_predictions_train = cb2.predict(X_train_smote)
cb2_predictions_test = cb2.predict(X_test_resampled)

accuracy_train = accuracy_score(y_train_smote, cb2_predictions_train)
print(f"CatBoost Classifier Train Accuracy: {accuracy_train:.2f}")
print("CatBoost Classifier Train Classification Report:")
print(classification_report(y_train_smote, cb2_predictions_train))
print("CatBoost Classifier Train Confusion Matrix:")
print(confusion_matrix(y_train_smote, cb2_predictions_train))

accuracy_test = accuracy_score(y_test_resampled, cb2_predictions_test)
print(f"CatBoost Classifier Test Accuracy: {accuracy_test:.2f}")
print("CatBoost Classifier Test Classification Report:")
print(classification_report(y_test_resampled, cb2_predictions_test))
print("CatBoost Classifier Test Confusion Matrix:")
print(confusion_matrix(y_test_resampled, cb2_predictions_test))

print(f"Selisih Akurasi: {abs(accuracy_train - accuracy_test):.2f}")

"""# feature importance"""

print("Melatih model CatBoost (cb2)...")

cb2 = CatBoostClassifier(
    iterations=800,
    depth=12,
    learning_rate=0.01,
    loss_function='Logloss',
    eval_metric='Accuracy',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=3
)
cb2.fit(X_train_smote, y_train_smote)
print("Model selesai dilatih.")

accuracy_test = cb2.score(X_test_resampled, y_test_resampled)
print(f"Akurasi Awal Model (cb2) di Data Tes: {accuracy_test:.4f}\n")

print("Menghitung Permutation Importance pada data tes untuk model CatBoost (cb2)...")
result = permutation_importance(
    cb2,
    X_test_resampled,
    y_test_resampled,
    n_repeats=10,
    random_state=42,
    n_jobs=-1,
    scoring='accuracy'
)
print("Perhitungan selesai.\n")


sorted_importances_idx = result.importances_mean.argsort()[::-1]

importance_summary = pd.DataFrame({
    'Fitur': X_test_resampled.columns[sorted_importances_idx],
    'Penurunan Akurasi': result.importances_mean[sorted_importances_idx],
    'Std Dev': result.importances_std[sorted_importances_idx]
})


importance_summary['Prediksi Akurasi Baru'] = accuracy_test - importance_summary['Penurunan Akurasi']

pd.options.display.float_format = '{:,.4f}'.format
print("="*80)
print("                  HASIL PERMUTATION IMPORTANCE (MODEL CATBOOST CB2)")
print(f"                  Akurasi Awal Model: {accuracy_test:.4f}")
print("="*80)
print("Menunjukkan estimasi akurasi jika sebuah fitur dihilangkan (diacak).")
print(importance_summary.to_string())
print("="*80)

cb3 = CatBoostClassifier(
    iterations=700,
    depth=12,
    learning_rate=0.02,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=3,
    border_count=128
)

cb3.fit(X_train_smote, y_train_smote)
cb3_predictions_train = cb3.predict(X_train_smote)
cb3_predictions_test = cb3.predict(X_test_resampled)

accuracy_train = accuracy_score(y_train_smote, cb3_predictions_train)
print(f"CatBoost Classifier Train Accuracy: {accuracy_train:.2f}")
print("CatBoost Classifier Train Classification Report:")
print(classification_report(y_train_smote, cb3_predictions_train))
print("CatBoost Classifier Train Confusion Matrix:")
print(confusion_matrix(y_train_smote, cb3_predictions_train))

accuracy_test = accuracy_score(y_test_resampled, cb3_predictions_test)
print(f"CatBoost Classifier Test Accuracy: {accuracy_test:.2f}")
print("CatBoost Classifier Test Classification Report:")
print(classification_report(y_test_resampled, cb3_predictions_test))
print("CatBoost Classifier Test Confusion Matrix:")
print(confusion_matrix(y_test_resampled, cb3_predictions_test))

print(f"Selisih Akurasi: {abs(accuracy_train - accuracy_test):.2f}")

"""# feature importance"""

print("Melatih model CatBoost (cb3)...")

cb3 = CatBoostClassifier(
    iterations=700,
    depth=12,
    learning_rate=0.02,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=3,
    border_count=128
)
cb3.fit(X_train_smote, y_train_smote)
print("Model selesai dilatih.")

accuracy_test = cb3.score(X_test_resampled, y_test_resampled)
print(f"Akurasi Awal Model (cb3) di Data Tes: {accuracy_test:.4f}\n")


print("Menghitung Permutation Importance pada data tes untuk model CatBoost (cb3)...")
result = permutation_importance(
    cb3,
    X_test_resampled,
    y_test_resampled,
    n_repeats=10,
    random_state=42,
    n_jobs=-1,
    scoring='accuracy'
)
print("Perhitungan selesai.\n")

sorted_importances_idx = result.importances_mean.argsort()[::-1]

importance_summary = pd.DataFrame({
    'Fitur': X_test_resampled.columns[sorted_importances_idx],
    'Penurunan Akurasi': result.importances_mean[sorted_importances_idx],
    'Std Dev': result.importances_std[sorted_importances_idx]
})

importance_summary['Prediksi Akurasi Baru'] = accuracy_test - importance_summary['Penurunan Akurasi']

pd.options.display.float_format = '{:,.4f}'.format
print("="*80)
print("                  HASIL PERMUTATION IMPORTANCE (MODEL CATBOOST CB3)")
print(f"                  Akurasi Awal Model: {accuracy_test:.4f}")
print("="*80)
print("Menunjukkan estimasi akurasi jika sebuah fitur dihilangkan (diacak).")
print(importance_summary.to_string())
print("="*80)

cb4 = CatBoostClassifier(
    iterations=900,
    depth=15,
    learning_rate=0.01,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=3,
    border_count=128,
    bagging_temperature=0.5
)
cb4.fit(X_train_smote, y_train_smote)
cb4_predictions_train = cb4.predict(X_train_smote)
cb4_predictions_test = cb4.predict(X_test_resampled)

accuracy_train = accuracy_score(y_train_smote, cb4_predictions_train)
print(f"CatBoost Classifier Train Accuracy: {accuracy_train:.2f}")
print("CatBoost Classifier Train Classification Report:")
print(classification_report(y_train_smote, cb4_predictions_train))
print("CatBoost Classifier Train Confusion Matrix:")
print(confusion_matrix(y_train_smote, cb4_predictions_train))

accuracy_test = accuracy_score(y_test_resampled, cb4_predictions_test)
print(f"CatBoost Classifier Test Accuracy: {accuracy_test:.2f}")
print("CatBoost Classifier Test Classification Report:")
print(classification_report(y_test_resampled, cb4_predictions_test))
print("CatBoost Classifier Test Confusion Matrix:")
print(confusion_matrix(y_test_resampled, cb4_predictions_test))

print(f"Selisih Akurasi: {abs(accuracy_train - accuracy_test):.2f}")

"""# feature importance"""

print("Melatih model CatBoost (cb4)...")
# Menggunakan hyperparameter yang Anda berikan untuk CatBoost
cb4 = CatBoostClassifier(
    iterations=900,
    depth=15,
    learning_rate=0.01,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0, # verbose=0 untuk menonaktifkan output saat training
    auto_class_weights='Balanced',
    l2_leaf_reg=3,
    border_count=128,
    bagging_temperature=0.5
)
cb4.fit(X_train_smote, y_train_smote)
print("Model selesai dilatih.")

# Menghitung akurasi awal pada data tes sebagai baseline
# .score() pada classifier akan menghitung akurasi secara default
accuracy_test = cb4.score(X_test_resampled, y_test_resampled)
print(f"Akurasi Awal Model (cb4) di Data Tes: {accuracy_test:.4f}\n")


# --- Bagian 3: Menghitung Permutation Importance ---
print("Menghitung Permutation Importance pada data tes untuk model CatBoost (cb4)...")
result = permutation_importance(
    cb4,
    X_test_resampled,
    y_test_resampled,
    n_repeats=10,
    random_state=42,
    n_jobs=-1, # Gunakan semua core CPU
    scoring='accuracy' # Secara eksplisit menggunakan akurasi sebagai metrik
)
print("Perhitungan selesai.\n")


# --- Bagian 4: Mengolah dan Menampilkan Hasil ---
# Mengurutkan fitur berdasarkan tingkat kepentingannya
sorted_importances_idx = result.importances_mean.argsort()[::-1]

# Membuat DataFrame ringkasan
importance_summary = pd.DataFrame({
    'Fitur': X_test_resampled.columns[sorted_importances_idx],
    'Penurunan Akurasi': result.importances_mean[sorted_importances_idx],
    'Std Dev': result.importances_std[sorted_importances_idx]
})

# Menambahkan kolom prediksi akurasi baru jika fitur dihilangkan
importance_summary['Prediksi Akurasi Baru'] = accuracy_test - importance_summary['Penurunan Akurasi']

# Menampilkan hasil akhir dalam format tabel yang rapi
pd.options.display.float_format = '{:,.4f}'.format
print("="*80)
print("                  HASIL PERMUTATION IMPORTANCE (MODEL CATBOOST CB4)")
print(f"                  Akurasi Awal Model: {accuracy_test:.4f}")
print("="*80)
print("Menunjukkan estimasi akurasi jika sebuah fitur dihilangkan (diacak).")
print(importance_summary.to_string())
print("="*80)

cb5 = CatBoostClassifier(
    iterations=1000,
    depth=15,
    learning_rate=0.005,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=5,
    border_count=256,
    bagging_temperature=0.7
)
cb5.fit(X_train_smote, y_train_smote)
cb5_predictions_train = cb5.predict(X_train_smote)
cb5_predictions_test = cb5.predict(X_test_resampled)

accuracy_train = accuracy_score(y_train_smote, cb5_predictions_train)
print(f"CatBoost Classifier Train Accuracy: {accuracy_train:.2f}")
print("CatBoost Classifier Train Classification Report:")
print(classification_report(y_train_smote, cb5_predictions_train))
print("CatBoost Classifier Train Confusion Matrix:")
print(confusion_matrix(y_train_smote, cb5_predictions_train))

accuracy_test = accuracy_score(y_test_resampled, cb5_predictions_test)
print(f"CatBoost Classifier Test Accuracy: {accuracy_test:.2f}")
print("CatBoost Classifier Test Classification Report:")
print(classification_report(y_test_resampled, cb5_predictions_test))
print("CatBoost Classifier Test Confusion Matrix:")
print(confusion_matrix(y_test_resampled, cb5_predictions_test))

print(f"Selisih Akurasi: {abs(accuracy_train - accuracy_test):.2f}")

"""# feature importance"""

print("Melatih model CatBoost (cb5)...")

cb5 = CatBoostClassifier(
    iterations=1000,
    depth=15,
    learning_rate=0.005,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=5,
    border_count=256,
    bagging_temperature=0.7
)
cb5.fit(X_train_smote, y_train_smote)
print("Model selesai dilatih.")

accuracy_test = cb5.score(X_test_resampled, y_test_resampled)
print(f"Akurasi Awal Model (cb5) di Data Tes: {accuracy_test:.4f}\n")

print("Menghitung Permutation Importance pada data tes untuk model CatBoost (cb5)...")
result = permutation_importance(
    cb5,
    X_test_resampled,
    y_test_resampled,
    n_repeats=10,
    random_state=42,
    n_jobs=-1,
    scoring='accuracy'
)
print("Perhitungan selesai.\n")

sorted_importances_idx = result.importances_mean.argsort()[::-1]

importance_summary = pd.DataFrame({
    'Fitur': X_test_resampled.columns[sorted_importances_idx],
    'Penurunan Akurasi': result.importances_mean[sorted_importances_idx],
    'Std Dev': result.importances_std[sorted_importances_idx]
})

importance_summary['Prediksi Akurasi Baru'] = accuracy_test - importance_summary['Penurunan Akurasi']

pd.options.display.float_format = '{:,.4f}'.format
print("="*80)
print("                  HASIL PERMUTATION IMPORTANCE (MODEL CATBOOST CB5)")
print(f"                  Akurasi Awal Model: {accuracy_test:.4f}")
print("="*80)
print("Menunjukkan estimasi akurasi jika sebuah fitur dihilangkan (diacak).")
print(importance_summary.to_string())
print("="*80)

"""visualisasi accuracy mode"""

models = ['Cb1', 'Cb2', 'Cb3', 'Cb4', 'Cb5']
train_accuracies = [0.80, 0.81, 0.83, 0.84, 0.82]
test_accuracies = [0.80, 0.80, 0.82, 0.84, 0.82]

bar_width = 0.4
x = np.arange(len(models))
plt.figure(figsize=(10, 6))
plt.bar(x - bar_width/2, train_accuracies, bar_width, label='Train Accuracy', color='#1f77b4')
plt.bar(x + bar_width/2, test_accuracies, bar_width, label='Test Accuracy', color='#2ca02c')


for i, (xt, yt) in enumerate(zip(x, train_accuracies)):
    plt.text(xt - bar_width/2, yt + 0.005, f'{yt:.2f}', ha='center', va='bottom', color='#1f77b4')
for i, (xt, yt) in enumerate(zip(x, test_accuracies)):
    plt.text(xt + bar_width/2, yt + 0.005, f'{yt:.2f}', ha='center', va='bottom', color='#2ca02c')


plt.xticks(x, models, fontsize=11)
plt.yticks(fontsize=11)
plt.xlabel('Model', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.title('Perbandingan Train dan Test Accuracy\nCB Classifiers', fontsize=14, fontweight='bold')
plt.ylim(0.78, 0.88)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(fontsize=11)
plt.tight_layout()

plt.show()

"""# Ensemble (voting)"""

rf1 = RandomForestClassifier(
    n_estimators=400,
    max_depth=15,
    min_samples_split=8,
    min_samples_leaf=6,
    max_features='sqrt',
    class_weight='balanced_subsample',
    random_state=42
)

cb3 = CatBoostClassifier(
    iterations=700,
    depth=12,
    learning_rate=0.02,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=3,
    border_count=128
)

ensemble_model1 = VotingClassifier(
    estimators=[('rf', rf1), ('cb', cb3)],
    voting='soft'
)

ensemble_model1.fit(X_train_smote, y_train_smote)

ensemble_predictions_train = ensemble_model1.predict(X_train_smote)
ensemble_predictions_test = ensemble_model1.predict(X_test_resampled)

accuracy_train = accuracy_score(y_train_smote, ensemble_predictions_train)
print(f"Ensemble Model Train Accuracy: {accuracy_train:.2f}")
print("Ensemble Model Train Classification Report:")
print(classification_report(y_train_smote, ensemble_predictions_train))
print("Ensemble Model Train Confusion Matrix:")
print(confusion_matrix(y_train_smote, ensemble_predictions_train))

accuracy_test = accuracy_score(y_test_resampled, ensemble_predictions_test)
print(f"Ensemble Model Test Accuracy: {accuracy_test:.2f}")
print("Ensemble Model Test Classification Report:")
print(classification_report(y_test_resampled, ensemble_predictions_test))
print("Ensemble Model Test Confusion Matrix:")
print(confusion_matrix(y_test_resampled, ensemble_predictions_test))

print(f"Selisih Akurasi: {abs(accuracy_train - accuracy_test):.2f}")

"""# feature importance"""

rf1 = RandomForestClassifier(
    n_estimators=400,
    max_depth=15,
    min_samples_split=8,
    min_samples_leaf=6,
    max_features='sqrt',
    class_weight='balanced_subsample',
    random_state=42
)

cb3 = CatBoostClassifier(
    iterations=700,
    depth=12,
    learning_rate=0.02,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=3,
    border_count=128
)

ensemble_model1 = VotingClassifier(
    estimators=[('rf', rf1), ('cb', cb3)],
    voting='soft'
)
ensemble_model1.fit(X_train_smote, y_train_smote)
print("Model selesai dilatih.")

accuracy_test = ensemble_model1.score(X_test_resampled, y_test_resampled)
print(f"Akurasi Awal Model (ensemble_model1) di Data Tes: {accuracy_test:.4f}\n")


print("Menghitung Permutation Importance pada data tes untuk model Ensemble...")
result = permutation_importance(
    ensemble_model1,
    X_test_resampled,
    y_test_resampled,
    n_repeats=10,
    random_state=42,
    n_jobs=-1,
    scoring='accuracy'
)
print("Perhitungan selesai.\n")


sorted_importances_idx = result.importances_mean.argsort()[::-1]

importance_summary = pd.DataFrame({
    'Fitur': X_test_resampled.columns[sorted_importances_idx],
    'Penurunan Akurasi': result.importances_mean[sorted_importances_idx],
    'Std Dev': result.importances_std[sorted_importances_idx]
})

importance_summary['Prediksi Akurasi Baru'] = accuracy_test - importance_summary['Penurunan Akurasi']

pd.options.display.float_format = '{:,.4f}'.format
print("="*80)
print("                  HASIL PERMUTATION IMPORTANCE (MODEL ENSEMBLE)")
print(f"                  Akurasi Awal Model: {accuracy_test:.4f}")
print("="*80)
print("Menunjukkan estimasi akurasi jika sebuah fitur dihilangkan (diacak).")
print(importance_summary.to_string())
print("="*80)

rf2 = RandomForestClassifier(
    n_estimators=500,
    max_depth=25,
    min_samples_split=2,
    min_samples_leaf=2,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42
)

cb4 = CatBoostClassifier(
    iterations=900,
    depth=15,
    learning_rate=0.01,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=3,
    border_count=128,
    bagging_temperature=0.5
)

# Buat ensemble model dengan soft voting
ensemble_model2 = VotingClassifier(
    estimators=[('rf', rf2), ('cb', cb5)],
    voting='soft'
)

# Fit model ensemble pada data train
ensemble_model2.fit(X_train_smote, y_train_smote)

# Prediksi pada data train dan test
ensemble_predictions_train = ensemble_model2.predict(X_train_smote)
ensemble_predictions_test = ensemble_model2.predict(X_test_resampled)

# Evaluasi akurasi
accuracy_train = accuracy_score(y_train_smote, ensemble_predictions_train)
print(f"Ensemble Model Train Accuracy: {accuracy_train:.2f}")
print("Ensemble Model Train Classification Report:")
print(classification_report(y_train_smote, ensemble_predictions_train))
print("Ensemble Model Train Confusion Matrix:")
print(confusion_matrix(y_train_smote, ensemble_predictions_train))

accuracy_test = accuracy_score(y_test_resampled, ensemble_predictions_test)
print(f"Ensemble Model Test Accuracy: {accuracy_test:.2f}")
print("Ensemble Model Test Classification Report:")
print(classification_report(y_test_resampled, ensemble_predictions_test))
print("Ensemble Model Test Confusion Matrix:")
print(confusion_matrix(y_test_resampled, ensemble_predictions_test))

print(f"Selisih Akurasi: {abs(accuracy_train - accuracy_test):.2f}")

"""# feature importance"""

# --- Bagian 2: Melatih Model Ensemble Anda (ensemble_model2) ---
print("Melatih model Ensemble (ensemble_model2)...")

# Mendefinisikan model-model individual
rf2 = RandomForestClassifier(
    n_estimators=500,
    max_depth=25,
    min_samples_split=2,
    min_samples_leaf=2,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42
)

cb4 = CatBoostClassifier(
    iterations=900,
    depth=15,
    learning_rate=0.01,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=3,
    border_count=128,
    bagging_temperature=0.5
)

# Mendefinisikan dan melatih model ensemble
# Catatan: Menggunakan 'cb4' sesuai definisi di atas.
ensemble_model2 = VotingClassifier(
    estimators=[('rf', rf2), ('cb', cb4)],
    voting='soft'
)
ensemble_model2.fit(X_train_smote, y_train_smote)
print("Model selesai dilatih.")

# Menghitung akurasi awal pada data tes sebagai baseline
accuracy_test = ensemble_model2.score(X_test_resampled, y_test_resampled)
print(f"Akurasi Awal Model (ensemble_model2) di Data Tes: {accuracy_test:.4f}\n")


# --- Bagian 3: Menghitung Permutation Importance ---
print("Menghitung Permutation Importance pada data tes untuk model Ensemble (ensemble_model2)...")
result = permutation_importance(
    ensemble_model2,
    X_test_resampled,
    y_test_resampled,
    n_repeats=10,
    random_state=42,
    n_jobs=-1, # Gunakan semua core CPU
    scoring='accuracy'
)
print("Perhitungan selesai.\n")


# --- Bagian 4: Mengolah dan Menampilkan Hasil ---
# Mengurutkan fitur berdasarkan tingkat kepentingannya
sorted_importances_idx = result.importances_mean.argsort()[::-1]

# Membuat DataFrame ringkasan
importance_summary = pd.DataFrame({
    'Fitur': X_test_resampled.columns[sorted_importances_idx],
    'Penurunan Akurasi': result.importances_mean[sorted_importances_idx],
    'Std Dev': result.importances_std[sorted_importances_idx]
})

# Menambahkan kolom prediksi akurasi baru jika fitur dihilangkan
importance_summary['Prediksi Akurasi Baru'] = accuracy_test - importance_summary['Penurunan Akurasi']

# Menampilkan hasil akhir dalam format tabel yang rapi
pd.options.display.float_format = '{:,.4f}'.format
print("="*80)
print("                  HASIL PERMUTATION IMPORTANCE (MODEL ENSEMBLE 2)")
print(f"                  Akurasi Awal Model: {accuracy_test:.4f}")
print("="*80)
print("Menunjukkan estimasi akurasi jika sebuah fitur dihilangkan (diacak).")
print(importance_summary.to_string())
print("="*80)

# Membuat visualisasi hasil
fig, ax = plt.subplots(figsize=(10, 8))
importance_summary.plot.barh(x='Fitur', y='Penurunan Akurasi', ax=ax, legend=False)
ax.set_title("Permutation Importance (Model Ensemble 2): Penurunan Akurasi")
ax.set_xlabel("Rata-rata Penurunan Akurasi")
ax.invert_yaxis()
fig.tight_layout()
plt.show()

# Definisikan model Random Forest dan CatBoost
rf3 = RandomForestClassifier(
    n_estimators=600,
    max_depth=20,
    min_samples_split=3,
    min_samples_leaf=3,
    max_features='log2',
    class_weight='balanced',
    random_state=42
)

cb5 = CatBoostClassifier(
    iterations=1000,
    depth=15,
    learning_rate=0.005,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=5,
    border_count=256,
    bagging_temperature=0.7
)

ensemble_model3 = VotingClassifier(
    estimators=[('rf', rf3), ('cb', cb6)],
    voting='soft'
)

ensemble_model3.fit(X_train_smote, y_train_smote)

ensemble_predictions_train = ensemble_model3.predict(X_train_smote)
ensemble_predictions_test = ensemble_model3.predict(X_test_resampled)

accuracy_train = accuracy_score(y_train_smote, ensemble_predictions_train)
print(f"Ensemble Model Train Accuracy: {accuracy_train:.2f}")
print("Ensemble Model Train Classification Report:")
print(classification_report(y_train_smote, ensemble_predictions_train))
print("Ensemble Model Train Confusion Matrix:")
print(confusion_matrix(y_train_smote, ensemble_predictions_train))

accuracy_test = accuracy_score(y_test_resampled, ensemble_predictions_test)
print(f"Ensemble Model Test Accuracy: {accuracy_test:.2f}")
print("Ensemble Model Test Classification Report:")
print(classification_report(y_test_resampled, ensemble_predictions_test))
print("Ensemble Model Test Confusion Matrix:")
print(confusion_matrix(y_test_resampled, ensemble_predictions_test))

print(f"Selisih Akurasi: {abs(accuracy_train - accuracy_test):.2f}")

"""# feature importance"""

print("Melatih model Ensemble (ensemble_model3)...")

# Mendefinisikan model-model individual
rf3 = RandomForestClassifier(
    n_estimators=600,
    max_depth=20,
    min_samples_split=3,
    min_samples_leaf=3,
    max_features='log2',
    class_weight='balanced',
    random_state=42
)

cb5 = CatBoostClassifier(
    iterations=1000,
    depth=15,
    learning_rate=0.005,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=0,
    auto_class_weights='Balanced',
    l2_leaf_reg=5,
    border_count=256,
    bagging_temperature=0.7
)

# Mendefinisikan dan melatih model ensemble
# Koreksi: Menggunakan cb5 yang sudah didefinisikan
ensemble_model3 = VotingClassifier(
    estimators=[('rf', rf3), ('cb', cb5)],
    voting='soft'
)
ensemble_model3.fit(X_train_smote, y_train_smote)
print("Model selesai dilatih.")

# Menghitung akurasi awal pada data tes sebagai baseline
accuracy_test = ensemble_model3.score(X_test_resampled, y_test_resampled)
print(f"Akurasi Awal Model (ensemble_model3) di Data Tes: {accuracy_test:.4f}\n")


# --- Bagian 3: Menghitung Permutation Importance ---
print("Menghitung Permutation Importance pada data tes untuk model Ensemble (ensemble_model3)...")
result = permutation_importance(
    ensemble_model3,
    X_test_resampled,
    y_test_resampled,
    n_repeats=10,
    random_state=42,
    n_jobs=-1, # Gunakan semua core CPU
    scoring='accuracy'
)
print("Perhitungan selesai.\n")


# --- Bagian 4: Mengolah dan Menampilkan Hasil ---
# Mengurutkan fitur berdasarkan tingkat kepentingannya
sorted_importances_idx = result.importances_mean.argsort()[::-1]

# Membuat DataFrame ringkasan
importance_summary = pd.DataFrame({
    'Fitur': X_test_resampled.columns[sorted_importances_idx],
    'Penurunan Akurasi': result.importances_mean[sorted_importances_idx],
    'Std Dev': result.importances_std[sorted_importances_idx]
})

# Menambahkan kolom prediksi akurasi baru jika fitur dihilangkan
importance_summary['Prediksi Akurasi Baru'] = accuracy_test - importance_summary['Penurunan Akurasi']

# Menampilkan hasil akhir dalam format tabel yang rapi
pd.options.display.float_format = '{:,.4f}'.format
print("="*80)
print("                  HASIL PERMUTATION IMPORTANCE (MODEL ENSEMBLE 3)")
print(f"                  Akurasi Awal Model: {accuracy_test:.4f}")
print("="*80)
print("Menunjukkan estimasi akurasi jika sebuah fitur dihilangkan (diacak).")
print(importance_summary.to_string())
print("="*80)

# Data akurasi untuk masing-masing model ensemble
models = ['ensemble_model1', 'ensemble_model2', 'ensemble_model3']
train_accuracies = [0.84, 0.91, 0.88]
test_accuracies = [0.84, 0.91, 0.88]

# Konstanta warna
TRAIN_COLOR = '#1f77b4'
TEST_COLOR = '#2ca02c'

# Buat histogram
bar_width = 0.4
x = np.arange(len(models))
plt.figure(figsize=(10, 6))
plt.bar(x - bar_width/2, train_accuracies, bar_width, label='Train Accuracy', color=TRAIN_COLOR)
plt.bar(x + bar_width/2, test_accuracies, bar_width, label='Test Accuracy', color=TEST_COLOR)

# Tambahkan label nilai di atas tiap batang
for i, (xt, yt) in enumerate(zip(x, train_accuracies)):
    plt.text(xt - bar_width/2, yt + 0.005, f'{yt:.2f}', ha='center', va='bottom', color=TRAIN_COLOR)
for i, (xt, yt) in enumerate(zip(x, test_accuracies)):
    plt.text(xt + bar_width/2, yt + 0.005, f'{yt:.2f}', ha='center', va='bottom', color=TEST_COLOR)

# Atur ticks, label, title, dan grid
plt.xticks(x, models, fontsize=11, rotation=15)
plt.yticks(fontsize=11)
plt.xlabel('Model Ensemble', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.title('Perbandingan Train dan Test Accuracy\nEnsemble Models', fontsize=14, fontweight='bold')
plt.ylim(0.80, 0.95)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(fontsize=11)
plt.tight_layout()

# Tampilkan grafik
plt.show()

"""#Visualisasi Grafik Accuracy Semua Model"""

models = ['rf1', 'rf2', 'rf3', 'Cb1', 'Cb2', 'Cb3', 'Cb5', 'Cb6', 'ensemble_model1', 'ensemble_model2', 'ensemble_model3']
train_accuracies = [0.85, 0.94, 0.90, 0.80, 0.81, 0.82, 0.83, 0.82, 0.84, 0.91, 0.88]
test_accuracies = [0.85, 0.94, 0.90, 0.80, 0.80, 0.82, 0.83, 0.81, 0.84, 0.91, 0.88]

plt.figure(figsize=(12, 6), dpi=200)


bar_width = 0.4
x = np.arange(len(models))
plt.bar(x - bar_width/2, train_accuracies, bar_width, label='Train Accuracy', color='#1f77b4')
plt.bar(x + bar_width/2, test_accuracies, bar_width, label='Test Accuracy', color='#2ca02c')


for i, (xt, yt) in enumerate(zip(x, train_accuracies)):
    plt.text(xt - bar_width/2, yt + 0.005, f'{yt:.2f}', ha='center', va='bottom', fontsize=10, fontweight='bold', color='#1f77b4')
for i, (xt, yt) in enumerate(zip(x, test_accuracies)):
    plt.text(xt + bar_width/2, yt + 0.005, f'{yt:.2f}', ha='center', va='bottom', fontsize=10, fontweight='bold', color='#2ca02c')


plt.xticks(x, models, rotation=45, ha='right', fontsize=11)
plt.yticks(fontsize=11)
plt.xlabel('Model', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.title('Perbandingan Train dan Test Accuracy Semua Model', fontsize=14, fontweight='bold')
plt.ylim(0.75, 1.00)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(fontsize=11)
plt.tight_layout()

plt.show()